// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api;

namespace api.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api.Todo", b =>
                {
                    b.Property<int>("todo_id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("is_done");

                    b.Property<string>("title");

                    b.HasKey("todo_id");

                    b.ToTable("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
